version: '3'

env:
  PLATEX: platex
  DVIPDF: dvipdfmx -p a5
  RM: rm

tasks:
  build:
    desc: Bulid PDF from TeX source.
    cmds:
      - $PLATEX haskellnote; $PLATEX haskellnote; $DVIPDF haskellnote
  clean:
    desc: Clean up intermediate files.
    cmds:
      - $RM *.aux *.dvi *.idx *.log *.toc
